2025-05-21 17:44:25,297 ERROR: Traceback (most recent call last):
  File "C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\app.py", line 326, in login
    return render_template('login.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\venv\Lib\site-packages\flask\templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\venv\Lib\site-packages\flask\templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\venv\Lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\templates\base.html", line 843, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\templates\login.html", line 39, in block 'content'
    <a href="{{ url_for('forgot_password') }}" class="btn btn-link">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\venv\Lib\site-packages\flask\app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\venv\Lib\site-packages\flask\app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\venv\Lib\site-packages\werkzeug\routing\map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'forgot_password'. Did you mean 'google_authorized' instead?
 [in C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\error_handlers.py:54]
2025-05-21 18:00:43,812 INFO: Action: login_manual_password_success, User: Yehia, Details: Password verified for user Yehia. Proceeding to 2FA. [in C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\app.py:761]
2025-05-21 18:01:03,613 INFO: Action: login_manual_2fa_failed, User: Yehia, Details: User Yehia failed 2FA. Invalid code. [in C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\app.py:761]
2025-05-21 18:01:12,847 INFO: Action: login_manual_2fa_failed, User: Yehia, Details: User Yehia failed 2FA. Invalid code. [in C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\app.py:761]
2025-05-21 18:01:22,107 INFO: Action: login_manual_2fa_success, User: Yehia, Details: User Yehia successfully completed 2FA and logged in manually. [in C:\Users\yehia\OneDrive\Desktop\FINNAAAAAAAAAAAAAAAAAAAAAAALLLLLLLLLLLL\DATA_INTEGRITY_FINAL_PROJECT-yehia\DATA_INTEGRITY_FINAL_PROJECT-yehia\app.py:761]
